# Generated by Django 6.0.6 on 2026-06-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='headline',
            field=models.CharField(blank=True, help_text='Frase de impacto do hero. Ex: Construo interfaces limpas e funcionais.', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='tagline',
            field=models.CharField(blank=True, help_text='Linha curta abaixo do headline, no hero.', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(help_text="Texto usado na seção 'Sobre mim' (pode ter múltiplos parágrafos)."),
        ),
    ]
