# Generated by Django 6.0.6 on 2026-06-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_spotifyauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_commits', models.PositiveIntegerField(default=0)),
                ('total_repos', models.PositiveIntegerField(default=0)),
                ('estimated_lines', models.PositiveBigIntegerField(default=0, help_text='Estimativa a partir dos bytes por linguagem (GitHub não expõe linhas reais).')),
                ('languages', models.JSONField(default=dict, help_text='Ex: {"Python": 45.2, "TypeScript": 30.1}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estatísticas do GitHub',
                'verbose_name_plural': 'Estatísticas do GitHub',
            },
        ),
    ]
