# Generated by Django 6.0.6 on 2026-06-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_githubstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubstats',
            name='total_stars',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
