# Generated by Django 6.0.6 on 2026-06-20 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_githubstats_total_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Aceita imagens estáticas e GIFs.', upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Mídia do projeto',
                'verbose_name_plural': 'Mídias do projeto',
                'ordering': ['order', 'id'],
            },
        ),
    ]
