# Generated by Django 6.0.6 on 2026-06-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_calendarentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='headline',
        ),
        migrations.AlterField(
            model_name='profile',
            name='tagline',
            field=models.CharField(blank=True, help_text='Linha curta abaixo da saudação, no hero.', max_length=300),
        ),
    ]
