# Generated by Django 6.0.6 on 2026-06-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_profile_headline_alter_profile_tagline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='recurring_clients',
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, help_text='Ex: Desenvolvedor Estagiário', max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='experience/')),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Deixe em branco se ainda estiver em andamento.', null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('technologies', models.ManyToManyField(blank=True, related_name='experiences', to='portfolio.technology')),
            ],
            options={
                'verbose_name': 'Experiência',
                'verbose_name_plural': 'Experiências',
                'ordering': ['order', '-start_date'],
            },
        ),
    ]
