# Generated by Django 6.0.6 on 2026-06-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_profile_recurring_clients_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('work', 'Profissional'), ('education', 'Acadêmica')], default='work', max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(help_text='Empresa (profissional) ou instituição de ensino (acadêmica).', max_length=120),
        ),
        migrations.AlterField(
            model_name='experience',
            name='role',
            field=models.CharField(blank=True, help_text='Ex: Desenvolvedor Estagiário, ou o nome do curso.', max_length=120),
        ),
    ]
