# Generated by Django 6.0.6 on 2026-06-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_experience_category_alter_experience_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubstats',
            name='contributions',
            field=models.JSONField(blank=True, default=dict, help_text='Mapa "AAAA-MM-DD" -> número de commits naquele dia, últimos ~12 meses (GitHub GraphQL).'),
        ),
    ]
